---
version: "2.1"
services:
  main_app:
    cpu_shares: 90
    command: []
    container_name: forge-kasm
    deploy:
      resources:
        limits:
          memory: 7801M
    image: ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy
    labels:
      icon: https://icon.casaos.io/main/all/baseimage-kasmvnc.png
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./forge-kasm/forge-kasm.sh
        target: /config
#     command: bash -c "./forge/forge.sh"
#    devices: []
#    shm_size: "4gb"
#    cap_add: []
#    environment: []
    network_mode: bridge
